import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { PLACES, RECEPTION } from './travel';
import type { GuestSide } from './travel';
import { ORIGINS, DIRECT, AIRPORTS, STATIONS, CHECKED, AIR_SOURCES, ARRIVAL_NAMES, flightSearch, railOptions } from './routes';
import type { Origin, AirportDestination, RailDestination } from './routes';

function Band() { return <div className="folk-band" aria-hidden="true"/>; }
function Arrow() { return <span aria-hidden="true">↗</span>; }
function OutLink({href,children,className=''}:{href:string;children:ReactNode;className?:string}) { return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}<Arrow/></a>; }
function Countdown() {
 const [now,setNow]=useState<number|null>(null);
 useEffect(()=>{let id:number|undefined; const tick=()=>{clearInterval(id);setNow(Date.now());if(!document.hidden)id=window.setInterval(()=>setNow(Date.now()),1000);};tick();document.addEventListener('visibilitychange',tick);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',tick);};},[]);
 const seconds=now===null?null:Math.max(0,Math.ceil((Date.parse('2026-11-30T00:00:00+05:30')-now)/1000));
 const units=seconds===null?[null,null,null,null]:[Math.floor(seconds/86400),Math.floor(seconds%86400/3600),Math.floor(seconds%3600/60),seconds%60];
 return <section className="countdown" aria-label="Wedding countdown"><div className="countdown-caption"><span lang="hi">शुभ घड़ी</span><h2>Almost<br/>{' '}<em>time.</em></h2></div><div><p className="eyebrow">THE COUNTDOWN TO 30 NOVEMBER</p><div className="timer" role="timer" aria-label="Time until the wedding" aria-live="off">{units.map((v,i)=><div key={i}><strong>{v===null?'—':String(v).padStart(2,'0')}</strong><span>{['Days','Hours','Minutes','Seconds'][i]}</span></div>)}</div><p className="timer-note">{seconds===0?(now!<Date.parse('2026-12-01T00:00:00+05:30')?'It’s wedding day!':'Our forever has begun.'):'30 November 2026 · Midnight IST'}</p></div><span className="countdown-end" aria-hidden="true">✳</span></section>;
}
function FlightCard({origin,to,onTrains}:{origin:Origin;to:AirportDestination;onTrains:()=>void}) {
 const local=origin.airportCode==='PAT';
 const airlines=DIRECT[to][origin.airportCode];
 const conflict=to==='DBR'&&origin.airportCode==='CCU';
 return <article className={`ticket flight-ticket ${to==='DBR'?'green-ticket':''}`}>
  <div className="ticket-heading"><span className="eyebrow">{to==='PAT'?'01 · THE CAPITAL GATEWAY':'02 · THE MITHILA GATEWAY'}</span><span className="travel-symbol" aria-hidden="true">✈</span></div>
  <h4>{AIRPORTS[to]} <span>Airport</span></h4>
  <div className="route-line"><div><strong>{origin.airportCode}</strong><span>{origin.airport}</span></div><div className="route-middle"><span aria-hidden="true">— ✈ —</span><small>{local?'Already in Bihar':airlines?'Nonstop listed':'Via Delhi · DEL'}</small></div><div><strong>{to}</strong><span>{AIRPORTS[to]}</span></div></div>
  <p className={`badge ${airlines?'direct':''}`}>{local?'Choose a local journey':airlines?'Published nonstop route':'Connection idea'}</p>
  <p className="carrier">{local?'Your journey starts in Bihar.':airlines||'IndiGo on both flight legs'}</p>
  <p className="ticket-note">{local?'Use the train guide below or arrange onward road travel to the celebrations.':airlines?'Choose your travel date to check flight numbers, fares and seats.':'Both legs are listed in published route networks. A same-day or through-ticket connection has not been verified; check dates and layovers.'}</p>
  {conflict&&<p className="route-caveat">IndiGo also advertises Kolkata–Darbhanga direct, but the route directory differs. <OutLink href="https://www.goindigo.in/domestic-flights/kolkata-to-darbhanga-flights.html">Check with IndiGo</OutLink></p>}
  <div className="ticket-bottom">{local?<button className="book-link local-train-button" onClick={onTrains}>Explore trains ↓</button>:<OutLink className="book-link" href={flightSearch(origin,to)}>Find flights</OutLink>}<details><summary>Route sources</summary><OutLink href={AIR_SOURCES[to]}>Published {to} routes</OutLink>{!airlines&&!local&&<OutLink href="https://www.flightconnections.com/flights-to-new-delhi-del">First leg to Delhi</OutLink>}<p>Researched {CHECKED}. General routes, not date-specific availability.</p></details></div>
 </article>;
}
function TrainCard({origin,to}:{origin:Origin;to:RailDestination}) {
 const routes=railOptions(origin,to);
 return <article className="ticket train-ticket"><div className="ticket-heading"><span className="station-code">{to}</span><span className="eyebrow">{to==='MFP'?'FOR THE WEDDING':'FOR THE GROOM’S SIDE'}</span></div><h4>{STATIONS[to]}</h4>{routes.map(({train:t,arrival,transfer})=><div className="train-service" key={t.number}><p className={`badge ${!transfer&&!origin.connectionOnly?'direct':''}`}>{transfer?'Train + onward travel':origin.connectionOnly?'After a separate connection':'Through train from boarding station'}</p><p className="train-number">{t.number}</p><h5>{t.name}</h5><p className="boarding">{t.from} <b>{t.fromCode}</b><span aria-hidden="true"> → </span>{ARRIVAL_NAMES[arrival]} <b>{arrival}</b></p>{transfer&&<p className="transfer-note">Then arrange a separate local train or road transfer to <strong>{STATIONS[to]} ({to})</strong>.{arrival==='NBJU'&&' NBJU is New Barauni, not Barauni Junction (BJU).'}</p>}<OutLink className="book-link" href={t.source}>Timetable & operating days</OutLink></div>)}<p className="rail-footnote">Selected service, not a complete list. Confirm your boarding date and seat availability on <OutLink href="https://www.irctc.co.in/nget/train-search">IRCTC</OutLink>.</p></article>;
}
function TravelGuide() {
 const [originId,setOriginId]=useState('delhi');
 const [mode,setMode]=useState<'flights'|'trains'>('flights');
 const origin=ORIGINS.find(o=>o.id===originId)!;
 return <section className="travel-section" id="travel" aria-labelledby="travel-title"><div className="travel-intro"><div><p className="eyebrow">02 / THE JOURNEY</p><h2 id="travel-title">All roads<br/><em>lead to Bihar.</em></h2></div><div className="travel-intro-note"><span lang="hi">पधारिए!</span><p>Pack your bags.<br/>We’ll save you a place.</p><a href="#route-planner">Find your way <span aria-hidden="true">↘</span></a></div></div>
  <div className="travel-book" id="route-planner"><div className="travel-book-top"><span>YOUR PASSAGE TO THE CELEBRATION</span><span>INDIA → BIHAR</span></div>
   <div className="travel-controls"><div className="origin-field"><label htmlFor="origin">Where are you coming from?</label><select id="origin" value={originId} onChange={e=>setOriginId(e.target.value)}>{ORIGINS.map(o=><option key={o.id} value={o.id}>{o.capital} · {o.state}</option>)}</select><p>28 states + Delhi · capital cities and their gateways</p></div><fieldset className="transport-toggle"><legend>Choose your journey</legend><label className={mode==='flights'?'active':''}><input type="radio" name="transport" checked={mode==='flights'} onChange={()=>setMode('flights')}/><span aria-hidden="true">✈</span> Flights</label><label className={mode==='trains'?'active':''}><input type="radio" name="transport" checked={mode==='trains'} onChange={()=>setMode('trains')}/><span aria-hidden="true">▤</span> Trains</label></fieldset></div>
   <div className="results-heading"><div><p className="eyebrow">YOUR STARTING POINT</p><h3>{origin.capital} <span>to Bihar</span></h3></div><span className="researched">Researched {CHECKED}</span></div>
   <div className="route-results" aria-live="polite" aria-atomic="false">
   {mode==='flights'?<><p className="gateway-note">{origin.airportNote||`Depart from ${origin.airport} (${origin.airportCode}).`} {origin.gatewaySource&&<OutLink href={origin.gatewaySource}>Gateway details</OutLink>}</p><div className="flights-grid">{(['PAT','DBR'] as const).map(to=><FlightCard key={`${origin.id}-${to}`} origin={origin} to={to} onTrains={()=>setMode('trains')}/>)}</div><p className="guide-note">After landing, arrange onward travel to Muzaffarpur for the wedding or Begusarai for the groom’s celebrations.</p><button className="switch-link" onClick={()=>setMode('trains')}>Prefer a train? Explore the three arrival stations →</button></>:<div id="train-guide"><p className="gateway-note">{origin.railNote||'Board at the station printed on your chosen service below.'} {origin.gatewaySource&&<OutLink href={origin.gatewaySource}>Connection source</OutLink>}</p><div className="trains-grid">{(['BGS','BJU','MFP'] as const).map(to=><TrainCard key={`${origin.id}-${to}`} origin={origin} to={to}/>)}</div><p className="guide-note">Weekly services need careful planning. Allow for overnight journeys, separate connections and onward travel to the venue. No seats or November departures are confirmed here.</p></div>}
   </div><div className="travel-book-bottom"><span aria-hidden="true">✦</span> Route guide · Check current schedules before booking. <span aria-hidden="true">✦</span></div>
  </div>
 </section>;
}
function Celebration() {
 const [side,setSide]=useState<GuestSide>('groom');
 const steps=side==='groom'?[
 ['30 NOV · 12 NOON','The baraat sets off','Begusarai → Muzaffarpur'],['30 NOVEMBER','Venus weds Payal','Ratna Banquet & Resort, Muzaffarpur'],['1 DECEMBER','Home, together','Muzaffarpur → Begusarai'],['RECEPTION','The joy continues',`Begusarai · ${RECEPTION.date}`]
 ]:[['30 NOVEMBER','A warm welcome','Join Payal’s family in Muzaffarpur'],['30 NOVEMBER','Venus weds Payal','Ratna Banquet & Resort'],['1 DECEMBER','A new beginning','The couple returns to Begusarai'],['RECEPTION','Celebrate once more',`Begusarai · ${RECEPTION.date}`]];
 return <section className={`celebration-section ${side}`} id="celebrations"><div className="celebration-intro"><p className="eyebrow">01 / THE CELEBRATIONS</p><h2>Two homes.<br/><em>One wedding.</em></h2><fieldset className="side-selector"><legend className="sr-only">Your side of the celebration</legend>{(['groom','bride'] as const).map(s=><label key={s} className={side===s?'selected':''}><input type="radio" name="side" checked={side===s} onChange={()=>setSide(s)}/><strong className="side-name">{s==='groom'?'Venus':'Payal'}</strong><span>{s==='groom'?'Groom’s side':'Bride’s side'}</span><small>{s==='groom'?'Begusarai':'Muzaffarpur'}</small></label>)}</fieldset><div className="portrait-pair"><button type="button" className="portrait groom-portrait" aria-label="Choose Venus’s side — groom, Begusarai" aria-pressed={side==='groom'} aria-controls="celebration-programme" onClick={()=>setSide('groom')}/><span lang="hi" aria-hidden="true">संग संग</span><button type="button" className="portrait bride-portrait" aria-label="Choose Payal’s side — bride, Muzaffarpur" aria-pressed={side==='bride'} aria-controls="celebration-programme" onClick={()=>setSide('bride')}/></div><p className="programme-caption">From the baraat to the homecoming.</p></div><ol className="celebration-grid" id="celebration-programme" aria-live="polite">{steps.map(([date,title,where],i)=><li key={`${side}-${i}`}><span className="step-number" aria-hidden="true">0{i+1}</span><div><p className="eyebrow">{date}</p><h3>{title}</h3><p>{where}</p></div><span className="step-flower" aria-hidden="true">{['✳','❋','✴','✳'][i]}</span></li>)}</ol></section>;

}
function Hero() {
 return <section className="invitation-hero" aria-labelledby="couple-names"><div className="hero-copy"><div className="hero-kicker"><span lang="hi">॥ शुभ विवाह ॥</span><span>BIHAR, INDIA · 2026</span></div><h1 id="couple-names"><span>Venus</span><i>&</i><span>Payal</span></h1><div className="hero-bottom"><p>With our families,<br/>we invite you to celebrate.</p><a className="hero-cta" href="#celebrations">You’re invited <span aria-hidden="true">↘</span></a></div></div><figure className="hero-painting"><img src="/mithila-celebration-1536.webp" srcSet="/mithila-celebration-640.webp 640w, /mithila-celebration-960.webp 960w, /mithila-celebration-1536.webp 1536w" sizes="(max-width:760px) 100vw, 52vw" width="1536" height="1024" alt="Intricate Madhubani peacocks, fish and lotus flowers painted in indigo, pink and marigold" fetchPriority="high"/><figcaption>MITHILA IN EVERY DETAIL. LOVE IN EVERY LINE.</figcaption><div className="date-seal"><span>MONDAY</span><strong>30</strong><span>NOVEMBER 2026</span></div></figure><div className="hero-side-note">BEGUSARAI / MUZAFFARPUR</div></section>;
}
function Ribbon(){return <div className="wedding-ribbon" aria-label="Venus and Payal, 30 November 2026"><div aria-hidden="true">{Array.from({length:4},(_,i)=><span key={i}>VENUS & PAYAL <b>✳</b> 30 NOVEMBER 2026 <b>✳</b> शुभ विवाह <b>✳</b></span>)}</div></div>}
export default function App() {
 return <div className="page-frame"><a className="skip-link" href="#travel">Skip to travel guide</a><Band/><header className="site-nav"><a className="wordmark" href="#home">V<span>❋</span>P</a><span className="nav-caption">THE WEDDING OF<br/>VENUS & PAYAL</span><nav aria-label="Main navigation"><a href="#celebrations">The celebrations</a><a href="#travel">Getting here <span aria-hidden="true">↗</span></a></nav></header><main id="home"><Hero/><Ribbon/><Countdown/><Celebration/><TravelGuide/><section className="venues-section" aria-labelledby="venues-title"><div className="venue-intro"><p className="eyebrow">03 / MEET US HERE</p><h2 id="venues-title">A place<br/><em>for you.</em></h2><span lang="hi">अतिथि देवो भवः</span></div><div className="venue-grid">{(['wedding','begusarai'] as const).map((k,i)=><article key={k}><p className="eyebrow">{k==='wedding'?'30 NOVEMBER · THE WEDDING':'BARAAT & RECEPTION'}</p><span className="venue-number" aria-hidden="true">0{i+1}</span><h3>{PLACES[k].title}</h3><p className="venue-city">{PLACES[k].city}</p><address>{PLACES[k].address}</address>{k==='begusarai'&&<p className="venue-detail">Baraat: 30 November, noon<br/>Reception: {RECEPTION.date}</p>}</article>)}</div></section></main><footer><Band/><div className="footer-art"><p lang="hi">स्नेहिल आमंत्रण</p><p>A little Bihar.<br/><em>A lot of love.</em></p><a href="#home">Venus & Payal <span aria-hidden="true">↑</span></a><span>30 NOVEMBER 2026 · WITH OUR FAMILIES</span></div><Band/></footer></div>;
}
