import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { PLACES, RECEPTION } from './travel';
import type { GuestSide } from './travel';
import { ORIGINS, DIRECT, AIRPORTS, STATIONS, CHECKED, AIR_SOURCES, ARRIVAL_NAMES, flightSearch, railOptions } from './routes';
import type { Origin, AirportDestination, RailDestination } from './routes';

function Flower({ small = false }: { small?: boolean }) {
 return <svg className={small ? 'flower small' : 'flower'} viewBox="0 0 100 100" aria-hidden="true"><g stroke="#35261b" strokeWidth="1.7">{Array.from({length:8},(_,i)=><ellipse key={i} cx="50" cy="24" rx="11" ry="22" fill={i%2?'#eeb942':'#b7372b'} transform={`rotate(${i*45} 50 50)`}/>)}<circle cx="50" cy="50" r="17" fill="#174a3d"/><circle cx="50" cy="50" r="10" fill="#f4c555"/><circle cx="50" cy="50" r="4" fill="#a52c24"/></g></svg>;
}
function Band() { return <div className="folk-band" aria-hidden="true"/>; }
function Arrow() { return <span aria-hidden="true">↗</span>; }
function OutLink({href,children,className=''}:{href:string;children:ReactNode;className?:string}) { return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}<Arrow/></a>; }
function Countdown() {
 const [now,setNow]=useState<number|null>(null);
 useEffect(()=>{let id:number|undefined; const tick=()=>{clearInterval(id);setNow(Date.now());if(!document.hidden)id=window.setInterval(()=>setNow(Date.now()),1000);};tick();document.addEventListener('visibilitychange',tick);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',tick);};},[]);
 const seconds=now===null?null:Math.max(0,Math.ceil((Date.parse('2026-11-30T00:00:00+05:30')-now)/1000));
 const units=seconds===null?[null,null,null,null]:[Math.floor(seconds/86400),Math.floor(seconds%86400/3600),Math.floor(seconds%3600/60),seconds%60];
 return <section className="countdown" aria-label="Wedding countdown"><Flower/><div><p className="eyebrow">THE WAIT FOR OUR FOREVER</p><div className="timer" role="timer" aria-label="Time until the wedding" aria-live="off">{units.map((v,i)=><div key={i}><strong>{v===null?'—':String(v).padStart(2,'0')}</strong><span>{['Days','Hours','Minutes','Seconds'][i]}</span></div>)}</div><p className="timer-note">{seconds===0?(now!<Date.parse('2026-12-01T00:00:00+05:30')?'It’s wedding day!':'Our forever has begun.'):'30 November 2026 · Midnight IST'}</p></div><Flower/></section>;
}
function FlightCard({origin,to,onTrains}:{origin:Origin;to:AirportDestination;onTrains:()=>void}) {
 const local=origin.airportCode==='PAT';
 const airlines=DIRECT[to][origin.airportCode];
 const conflict=to==='DBR'&&origin.airportCode==='CCU';
 return <article className={`ticket flight-ticket ${to==='DBR'?'green-ticket':''}`}>
  <div className="ticket-heading"><span className="eyebrow">{to==='PAT'?'01 · THE CAPITAL GATEWAY':'02 · THE MITHILA GATEWAY'}</span><span className="travel-symbol" aria-hidden="true">✈</span></div>
  <h4>{AIRPORTS[to]} <span>Airport</span></h4>
  <div className="route-line"><div><strong>{origin.airportCode}</strong><span>{origin.airport}</span></div><div className="route-middle"><span aria-hidden="true">— ✈ —</span><small>{local?'Already in Bihar':airlines?'Nonstop listed':'Via Delhi · DEL'}</small></div><div><strong>{to}</strong><span>{AIRPORTS[to]}</span></div></div>
  <p className={`badge ${airlines?'direct':''}`}>{local?'Choose a local journey':airlines?'Published nonstop route':'Connection idea'}</p>
  <p className="carrier">{local?'Your journey starts in Bihar.':airlines||'IndiGo on both flight legs'}</p>
  <p className="ticket-note">{local?'Use the train guide below or arrange onward road travel to the celebrations.':airlines?'Choose your travel date to check flight numbers, fares and seats.':'Both legs are listed in published route networks. A same-day or through-ticket connection has not been verified; check dates and layovers.'}</p>
  {conflict&&<p className="route-caveat">IndiGo also advertises Kolkata–Darbhanga direct, but the route directory differs. <OutLink href="https://www.goindigo.in/domestic-flights/kolkata-to-darbhanga-flights.html">Check with IndiGo</OutLink></p>}
  <div className="ticket-bottom">{local?<button className="book-link local-train-button" onClick={onTrains}>Explore trains ↓</button>:<OutLink className="book-link" href={flightSearch(origin,to)}>Find flights</OutLink>}<details><summary>Route sources</summary><OutLink href={AIR_SOURCES[to]}>Published {to} routes</OutLink>{!airlines&&!local&&<OutLink href="https://www.flightconnections.com/flights-to-new-delhi-del">First leg to Delhi</OutLink>}<p>Researched {CHECKED}. General routes, not date-specific availability.</p></details></div>
 </article>;
}
function TrainCard({origin,to}:{origin:Origin;to:RailDestination}) {
 const routes=railOptions(origin,to);
 return <article className="ticket train-ticket"><div className="ticket-heading"><span className="station-code">{to}</span><span className="eyebrow">{to==='MFP'?'FOR THE WEDDING':'FOR THE GROOM’S SIDE'}</span></div><h4>{STATIONS[to]}</h4>{routes.map(({train:t,arrival,transfer})=><div className="train-service" key={t.number}><p className={`badge ${!transfer&&!origin.connectionOnly?'direct':''}`}>{transfer?'Train + onward travel':origin.connectionOnly?'After a separate connection':'Through train from boarding station'}</p><p className="train-number">{t.number}</p><h5>{t.name}</h5><p className="boarding">{t.from} <b>{t.fromCode}</b><span aria-hidden="true"> → </span>{ARRIVAL_NAMES[arrival]} <b>{arrival}</b></p>{transfer&&<p className="transfer-note">Then arrange a separate local train or road transfer to <strong>{STATIONS[to]} ({to})</strong>.{arrival==='NBJU'&&' NBJU is New Barauni, not Barauni Junction (BJU).'}</p>}<OutLink className="book-link" href={t.source}>Timetable & operating days</OutLink></div>)}<p className="rail-footnote">Selected service, not a complete list. Confirm your boarding date and seat availability on <OutLink href="https://www.irctc.co.in/nget/train-search">IRCTC</OutLink>.</p></article>;
}
function TravelGuide() {
 const [originId,setOriginId]=useState('delhi');
 const [mode,setMode]=useState<'flights'|'trains'>('flights');
 const origin=ORIGINS.find(o=>o.id===originId)!;
 return <section className="travel-section" id="travel" aria-labelledby="travel-title"><div className="section-title"><Flower small/><div><p className="eyebrow">FROM YOUR CITY, TO OUR CELEBRATION</p><h2 id="travel-title">Come, be a part of our story.</h2><p>Across India, all roads lead to a little more love.</p></div><Flower small/></div>
  <div className="travel-book"><div className="travel-book-top"><span lang="hi">पधारिए हमारे बिहार</span><span>THE WEDDING TRAVEL GUIDE</span><Flower small/></div>
   <div className="travel-controls"><div className="origin-field"><label htmlFor="origin">Where are you coming from?</label><select id="origin" value={originId} onChange={e=>setOriginId(e.target.value)}>{ORIGINS.map(o=><option key={o.id} value={o.id}>{o.capital} · {o.state}</option>)}</select><p>28 states + Delhi · capital cities and their gateways</p></div><fieldset className="transport-toggle"><legend>Choose your journey</legend><label className={mode==='flights'?'active':''}><input type="radio" name="transport" checked={mode==='flights'} onChange={()=>setMode('flights')}/><span aria-hidden="true">✈</span> Flights</label><label className={mode==='trains'?'active':''}><input type="radio" name="transport" checked={mode==='trains'} onChange={()=>setMode('trains')}/><span aria-hidden="true">▤</span> Trains</label></fieldset></div>
   <div className="results-heading"><div><p className="eyebrow">YOUR STARTING POINT</p><h3>{origin.capital} <span>to Bihar</span></h3></div><span className="researched">Researched {CHECKED}</span></div>
   <div className="route-results" aria-live="polite" aria-atomic="false">
   {mode==='flights'?<><p className="gateway-note">{origin.airportNote||`Depart from ${origin.airport} (${origin.airportCode}).`} {origin.gatewaySource&&<OutLink href={origin.gatewaySource}>Gateway details</OutLink>}</p><div className="flights-grid">{(['PAT','DBR'] as const).map(to=><FlightCard key={`${origin.id}-${to}`} origin={origin} to={to} onTrains={()=>setMode('trains')}/>)}</div><p className="guide-note">After landing, arrange onward travel to Muzaffarpur for the wedding or Begusarai for the groom’s celebrations.</p><button className="switch-link" onClick={()=>setMode('trains')}>Prefer a train? Explore the three arrival stations →</button></>:<div id="train-guide"><p className="gateway-note">{origin.railNote||'Board at the station printed on your chosen service below.'} {origin.gatewaySource&&<OutLink href={origin.gatewaySource}>Connection source</OutLink>}</p><div className="trains-grid">{(['BGS','BJU','MFP'] as const).map(to=><TrainCard key={`${origin.id}-${to}`} origin={origin} to={to}/>)}</div><p className="guide-note">Weekly services need careful planning. Allow for overnight journeys, separate connections and onward travel to the venue. No seats or November departures are confirmed here.</p></div>}
   </div><div className="travel-book-bottom"><span aria-hidden="true">✦</span> Published routes, thoughtfully gathered. Check the latest schedule before booking. <span aria-hidden="true">✦</span></div>
  </div>
 </section>;
}
function Celebration() {
 const [side,setSide]=useState<GuestSide>('groom');
 const steps=side==='groom'?[
 ['30 NOV · 12 NOON','The baraat sets off','Begusarai → Muzaffarpur'],['30 NOVEMBER','Venus weds Payal','Ratna Banquet & Resort, Muzaffarpur'],['1 DECEMBER','Home, together','Muzaffarpur → Begusarai'],['RECEPTION','The joy continues',`Begusarai · ${RECEPTION.date}`]
 ]:[['30 NOVEMBER','A warm welcome','Join Payal’s family in Muzaffarpur'],['30 NOVEMBER','Venus weds Payal','Ratna Banquet & Resort'],['1 DECEMBER','A new beginning','The couple returns to Begusarai'],['RECEPTION','Celebrate once more',`Begusarai · ${RECEPTION.date}`]];
 return <section className="celebration-section" id="celebrations"><div className="section-title"><Flower small/><div><p className="eyebrow">TWO HOMETOWNS. ONE BEAUTIFUL BEGINNING.</p><h2>A celebration on both sides.</h2></div><Flower small/></div><fieldset className="side-selector"><legend className="sr-only">Your side of the celebration</legend>{(['groom','bride'] as const).map(s=><label key={s} className={side===s?'selected':''}><input type="radio" name="side" checked={side===s} onChange={()=>setSide(s)}/><span>{s==='groom'?'Groom’s side':'Bride’s side'}</span><small>{s==='groom'?'Begusarai':'Muzaffarpur'}</small></label>)}</fieldset><ol className="celebration-grid">{steps.map(([date,title,where],i)=><li key={`${side}-${i}`}><span className="step-flower" aria-hidden="true">✦</span><p className="eyebrow">{date}</p><h3>{title}</h3><p>{where}</p></li>)}</ol></section>;
}
export default function App() {
 return <div className="page-frame"><a className="skip-link" href="#travel">Skip to travel guide</a><Band/><header className="site-nav"><a className="wordmark" href="#home">V <em>&</em> P</a><nav aria-label="Main navigation"><a href="#celebrations">Celebrations</a><a href="#travel">Travel guide</a></nav><span className="nav-date">30 · 11 · 2026</span></header><main id="home"><section className="invitation-hero" aria-labelledby="couple-names"><img src="/madhubani-invitation-1440.webp" srcSet="/madhubani-invitation-720.webp 720w, /madhubani-invitation-1440.webp 1440w, /madhubani-invitation-2172.webp 2172w" sizes="(min-width:1400px) 1320px, calc(100vw - 36px)" width="2172" height="724" alt="Madhubani bride and groom surrounded by peacocks, fish, lotus flowers and painted vines" fetchPriority="high"/><div className="hero-copy"><p className="blessing" lang="hi">॥ शुभ विवाह ॥</p><p className="eyebrow">WITH LOVE, FROM BIHAR</p><h1 id="couple-names">Venus <em>&</em> Payal</h1><div className="hero-rule" aria-hidden="true">✦ ━━━ ◆ ━━━ ✦</div><p className="hero-date">30 November 2026</p><p className="hometowns">Begusarai <span>♥</span> Muzaffarpur</p></div></section><Countdown/><Band/><Celebration/><TravelGuide/><section className="venues-section" aria-labelledby="venues-title"><div className="section-title"><Flower small/><div><p className="eyebrow">WE’LL BE WAITING FOR YOU</p><h2 id="venues-title">Our places of celebration.</h2></div><Flower small/></div><div className="venue-grid">{(['wedding','begusarai'] as const).map(k=><article key={k}><p className="eyebrow">{k==='wedding'?'THE WEDDING · 30 NOVEMBER':'BARAAT & RECEPTION'}</p><h3>{PLACES[k].title}</h3><p className="venue-city">{PLACES[k].city}</p><address>{PLACES[k].address}</address>{k==='begusarai'&&<p className="venue-detail">Baraat: 30 November, noon<br/>Reception: {RECEPTION.date}</p>}</article>)}</div></section></main><footer><Band/><div className="footer-art"><p lang="hi">स्नेहिल आमंत्रण</p><p>Come for the wedding.<br/><em>Stay for the memories.</em></p><span>Venus & Payal · Bihar · 2026</span></div><Band/></footer></div>;
}
